letak_player(18,16).
legendary_to_beat(3).
list_monsta([Dragonflymon]).
monsta_owned(Dragonflymon).
monsta_owned_health(Dragonflymon,150).
numMonsta(1)numMonsta(1)
player_bag([whiteLilyPerfume]).
whiteLilyPerfumeC(10).
numItems(1).
checkGym(0).
cave(18,17).
wlEffect(0).
